### ISSUE TITLE
graphviz-2999.20.0.1 does not compile with GHC 8.0.x

### ISSUE THREAD

**Issue by peti** [ivan-m/graphviz#34]
Citing from https://hydra.nixos.org/build/74574307:

~~~
Data/GraphViz/Printing.hs:135:13: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘PP.<>’,
                             imported from ‘Text.PrettyPrint.Leijen.Text.Monadic’ at Data/GraphViz/Printing.hs:(79,1)-(85,68)
                          or ‘Data.Semigroup.<>’,
                             imported from ‘Data.Semigroup’ at Data/GraphViz/Printing.hs:105:24-36

Data/GraphViz/Printing.hs:285:16: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘PP.<>’,
                             imported from ‘Text.PrettyPrint.Leijen.Text.Monadic’ at Data/GraphViz/Printing.hs:(79,1)-(85,68)
                          or ‘Data.Semigroup.<>’,
                             imported from ‘Data.Semigroup’ at Data/GraphViz/Printing.hs:105:24-36

Data/GraphViz/Printing.hs:285:21: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘PP.<>’,
                             imported from ‘Text.PrettyPrint.Leijen.Text.Monadic’ at Data/GraphViz/Printing.hs:(79,1)-(85,68)
                          or ‘Data.Semigroup.<>’,
                             imported from ‘Data.Semigroup’ at Data/GraphViz/Printing.hs:105:24-36

Data/GraphViz/Printing.hs:288:26: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘PP.<>’,
                             imported from ‘Text.PrettyPrint.Leijen.Text.Monadic’ at Data/GraphViz/Printing.hs:(79,1)-(85,68)
                          or ‘Data.Semigroup.<>’,
                             imported from ‘Data.Semigroup’ at Data/GraphViz/Printing.hs:105:24-36

Data/GraphViz/Printing.hs:288:35: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘PP.<>’,
                             imported from ‘Text.PrettyPrint.Leijen.Text.Monadic’ at Data/GraphViz/Printing.hs:(79,1)-(85,68)
                          or ‘Data.Semigroup.<>’,
                             imported from ‘Data.Semigroup’ at Data/GraphViz/Printing.hs:105:24-36

Data/GraphViz/Printing.hs:291:25: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘PP.<>’,
                             imported from ‘Text.PrettyPrint.Leijen.Text.Monadic’ at Data/GraphViz/Printing.hs:(79,1)-(85,68)
                          or ‘Data.Semigroup.<>’,
                             imported from ‘Data.Semigroup’ at Data/GraphViz/Printing.hs:105:24-36

Data/GraphViz/Printing.hs:291:35: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘PP.<>’,
                             imported from ‘Text.PrettyPrint.Leijen.Text.Monadic’ at Data/GraphViz/Printing.hs:(79,1)-(85,68)
                          or ‘Data.Semigroup.<>’,
                             imported from ‘Data.Semigroup’ at Data/GraphViz/Printing.hs:105:24-36

Data/GraphViz/Printing.hs:348:37: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘PP.<>’,
                             imported from ‘Text.PrettyPrint.Leijen.Text.Monadic’ at Data/GraphViz/Printing.hs:(79,1)-(85,68)
                          or ‘Data.Semigroup.<>’,
                             imported from ‘Data.Semigroup’ at Data/GraphViz/Printing.hs:105:24-36
~~~

**Comment by ivan-m** [comment]
That's odd, because [it builds for me on Travis-CI](https://travis-ci.org/ivan-m/graphviz/builds/382513356).

Is the Nix expression doing any jailbreaking, etc.?

Note that it should be using `wl-pprint-text-1.2.*` (as it no longer exports `Text.PrettyPrint.Leijen.Text.Monadic.<>`), which makes me think this is due to removal of version bounds.

**Comment by peti** [comment]
You are right, we still had a jailbreak in place in Nix to work around the constraint on previous versions of `QuickCheck`, but I see that issue no longer exists. When we build the package with `wl-pprint-text-1.2.*`, the build succeeds, indeed. I do run into test suite failures, however, because the test suite has an undeclared dependency on the `neato` executable:

~~~
  tests/Data/GraphVizSpec.hs:27:
  1) Data.GraphViz FGL Graphs are augmentable
       uncaught exception: IOException of type NoSuchThing (neato: runInteractiveProcess: runInteractiveProcess: exec: does not exist (No such file or directory)) (after 1 test)
       mkGraph [] []

  tests/Data/GraphVizSpec.hs:29:
  2) Data.GraphViz Ensure augmentation is valid
       uncaught exception: IOException of type NoSuchThing (neato: runInteractiveProcess: runInteractiveProcess: exec: does not exist (No such file or directory)) (after 1 test)
       mkGraph [] []

  tests/Data/GraphVizSpec.hs:31:
  3) Data.GraphViz Unique edges in augmented FGL Graphs
       uncaught exception: IOException of type NoSuchThing (neato: runInteractiveProcess: runInteractiveProcess: exec: does not exist (No such file or directory)) (after 1 test)
       mkGraph [] []
~~~

**Comment by peti** [comment]
Fixed in https://github.com/peti/nixpkgs/commit/28c30b81a4852c408f302953f03540b8d062a092. Thank you for your help!
