### ISSUE TITLE
Build failure with GHC-8.4.1 

### ISSUE THREAD

**Issue by recursion-ninja** [ivan-m/graphviz#31]
`graphviz` cannot be build using `ghc-8.4.1` due to a build failure of it's dependency `wl-pprint-text` with `ghc-8-4-1`.

**Comment by ivan-m** [comment]
See #30

**Comment by geh** [comment]
I am still getting a compile error with GHC 8.4.1 and wl-pprint-text 1.1.1.1:

~~~
[ 7 of 31] Compiling Data.GraphViz.Printing ( Data/GraphViz/Printing.hs, dist/build/Data/GraphViz/Printing.o )

Data/GraphViz/Printing.hs:232:16: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at Data/GraphViz/Printing.hs:48:8-29
                             (and originally defined in ‘GHC.Base’)
                          or ‘PP.<>’,
                             imported from ‘Text.PrettyPrint.Leijen.Text.Monadic’ at Data/GraphViz/Printing.hs:(75,1)-(81,68)
    |
232 | wrap b a d = b <> d <> a
    |                ^^
~~~

**Comment by ivan-m** [comment]
Yes, because I haven't updated graphviz yet.
