### ISSUE TITLE
cannot build with ghc-9.4: Data/Graph/Inductive/Monad/STArray.hs:64:10: error: No instance for (MonadFail (ST s))

### ISSUE THREAD

**Issue by jwaldmann** [ivan-m/graphviz#57]
Oh, sorry, it's for fgl. https://github.com/haskell/fgl/issues/103

```
cabal build --with-ghc=/opt/ghc/ghc-9.4.1/bin/ghc --allow-newer
...
[ 9 of 29] Compiling Data.Graph.Inductive.Monad.STArray ( Data/Graph/Inductive/Monad/STArray.hs, dist/build/Data/Graph/Inductive/Monad/STArray.o, dist/build/Data/Graph/Inductive/Monad/STArray.dyn_o )

Data/Graph/Inductive/Monad/STArray.hs:64:10: error:
    • No instance for (MonadFail (ST s))
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘GraphM (ST s) (SGr s)’
   |
64 | instance GraphM (ST s) (SGr s) where
   |          ^^^^^^^^^^^^^^^^^^^^^
```
