### ISSUE TITLE
Data/GraphViz/Types/Printing.hs:152:16: error: Error: Ambiguous occurrence ‘<>’

### ISSUE THREAD

**Issue by juhp** [ivan-m/graphviz#54]
graphviz failed to cabal build with ghc-9.2:

see https://github.com/juhp/fbrnch/commit/9df2aea9f1de93f3ee5ab5eebeff9e1426237ecd

Here is part of the error output:
```
Data/GraphViz/Types/Parsing.hs:303:22: warning: [-Wunused-do-bind]
Warning:     A do-notation statement discarded a result of type ‘String’
    Suppress this warning by saying ‘_ <- whitespace'’
    |
303 |                      whitespace'
    |                      ^^^^^^^^^^^
[3 of 8] Compiling Data.GraphViz.Types.Printing ( Data/GraphViz/Types/Printing.hs, dist/build/Data/GraphViz/Types/Printing.o, dist/build/Data/GraphViz/Types/Printing.dyn_o )

Data/GraphViz/Types/Printing.hs:152:16: error:
Error:     Ambiguous occurrence ‘<>’
    It could refer to
       either ‘Prelude.<>’,
              imported from ‘Prelude’ at Data/GraphViz/Types/Printing.hs:38:8-35
              (and originally defined in ‘GHC.Base’)
           or ‘Text.PrettyPrint.<>’,
              imported from ‘Text.PrettyPrint’ at Data/GraphViz/Types/Printing.hs:(51,1)-(58,32)
              (and originally defined in ‘Text.PrettyPrint.HughesPJ’)
    |
152 | wrap b a d = b <> d <> a
    |                ^^

Data/GraphViz/Types/Printing.hs:152:21: error:
Error:     Ambiguous occurrence ‘<>’
    It could refer to
       either ‘Prelude.<>’,
              imported from ‘Prelude’ at Data/GraphViz/Types/Printing.hs:38:8-35
              (and originally defined in ‘GHC.Base’)
           or ‘Text.PrettyPrint.<>’,
              imported from ‘Text.PrettyPrint’ at Data/GraphViz/Types/Printing.hs:(51,1)-(58,32)
              (and originally defined in ‘Text.PrettyPrint.HughesPJ’)
    |
152 | wrap b a d = b <> d <> a
    |                     ^^
```
